# Google App Engine deployment (Free tier available)
runtime: python39

env_variables:
  FLASK_ENV: production
  PORT: 8080

handlers:
- url: /.*
  script: auto
  
automatic_scaling:
  min_instances: 0
  max_instances: 1