[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python app.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[env]
PORT = "5000"
FLASK_ENV = "production"