services:
  - type: web
    name: nasa-aqi-backend
    env: python
    buildCommand: "cd backend && pip install -r requirements.txt"
    startCommand: "cd backend && python app.py"
    plan: free
    healthCheckPath: /api/health
    envVars:
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production